Profile page creation
Code-the-Dream-School/ffprac-team7-front pull request #39
Opened 2024-04-18 22:46 UTC by Maarimar

2024-04-19 01:42 UTC, alejandroo-pc commented on src/pages/ProfilePage.jsx
> +const [currentProfile, setCurrentProfile] = useState(profiles[0])
when I change the state of the profile to something like `useState(profiles[1])` the fields update accordingly.
So, the implementation in the jsx should also work when we map over real users.

Good start and styling!

2024-04-19 01:42 UTC, alejandroo-pc commented on src/styles/ProfilePage.css
> +.imgProfile{
This is some great styling, I think it follows the figma designs!
One small adjustment, the profile picture sits to the left and I think it could be centered in this page.

2024-04-19 13:55 UTC, royemosby requested changes
@Maarimar As soon as the merge conflict is resolved, I'll merge this in 👍

2024-04-22 07:56 UTC, royemosby approved these changes
looks good!

2024-04-22 07:56 UTC, merged