Filter displayed items
Code-the-Dream-School/ffprac-team7-front pull request #41
Opened 2024-04-19 15:23 UTC by up2code3

Title and Date Search bar for found items 

note, date is year-month-day example 2024-19-04

2024-04-19 15:43 UTC, royemosby requested changes
The search functionality works great! I think it would be a good idea if you displayed something along the lines of "No search results" when there are 0 items to display. At a minimum you can create a 2em paragraph with centered text. That would be GTG but you can do something more elaborate if you like!

2024-04-19 16:31 UTC, alejandroo-pc commented on src/pages/Items.jsx
> +        <div className="reportedItemsContainer">
This is a great approach! When we implement logic connecting the backend it should be an easy transition.

2024-04-19 16:31 UTC, alejandroo-pc commented on src/styles/Items.css
>  .dateLostFound {
good use of descriptive classnames, this will help scope styling down to specific components!

2024-04-19 21:45 UTC, up2code3 commented
should be good to go.

2024-04-20 12:20 UTC, royemosby approved these changes
👍

2024-04-20 12:20 UTC, merged