fetching items but no filter display also crashed atm
Code-the-Dream-School/ffprac-team7-front pull request #53
Opened 2024-04-28 02:26 UTC by up2code3

2024-04-28 04:25 UTC, alejandroo-pc requested changes
Almost there Tristan! 
You have been killing it on this ticket 😤  just a few more tweaks and we can ship it! 🚢 

Let me know if the additional UI tweaks are too much to do at this moment.

2024-04-28 04:25 UTC, alejandroo-pc commented on src/pages/Items.jsx
> +          item.title && item.title.toLowerCase().includes(filter.toLowerCase())
I would change the filtering by `tittle` to `_id`. I know I suggested that but forgot to change it after I got the rendering to work. 

The reason being, two posts may have the same title and we don't want to render them twice.

2024-04-28 04:25 UTC, alejandroo-pc commented on src/pages/Items.jsx
>      <div>
There are some issues with the UI, which considering the limited time we have I suggest adding the change in this PR. The posts overlap each other so I suggest adding some padding/spacing to the items-container.

2024-04-28 04:30 UTC, royemosby commented
Can you also add a summary of changes in the description?

2024-04-28 12:45 UTC, up2code3 commented on src/pages/Items.jsx
> +          item.title && item.title.toLowerCase().includes(filter.toLowerCase())
I get the logic of preventing 2 items with the sam ename, but I am confused about how users would search by id? or will the users still search by title, but the results will be by id?

2024-04-28 12:48 UTC, up2code3 commented on src/pages/Items.jsx
> +          item.title && item.title.toLowerCase().includes(filter.toLowerCase())
I made the change, but I am a bit confused about , how the users will know the item id? Will you be available later today?

2024-04-28 19:40 UTC, alejandroo-pc requested changes
Great work Tristan! The app is looking great and we're almost ready for prod! 
The only functionality left is to redirect users to the claim items page after clicking on a lost item.

2024-04-28 19:40 UTC, alejandroo-pc commented on src/pages/Items.jsx
> +        <button className="button" onClick={() => handleLostFilter(false)}>
I think we want to add a <Link> to each item card, so that the user is redirected to the claim items page. 
Currently, we render the list of items, but the user isn't able to interact with the lost items. 

Besides that, everything looks great 🙌🏼

2024-04-30 00:42 UTC, royemosby approved these changes
👍

2024-04-30 01:20 UTC, merged